### ISSUE TITLE
Example with auth

### ISSUE THREAD

**Issue by ignusius** [knusbaum/go9p#1]
Would you write example with Auth, pleace?

**Comment by knusbaum** [comment]
Unfortunately, the auth is basically non-functional if my memory serves me. I was working on integrating factotum from p9p for a while, but dropped it before I finished. There is some work done in this repo, so it could be finished, but I'm not sure how much work is left to get it working.

**Comment by knusbaum** [comment]
@ignusius 

I know this ticket is super old, but in case you're interested, auth should now work with factotum for servers written with go9p v1.5.0 and newer.

If you pass the `WithAuth` option when calling `NewFS`, everything will be handled automatically, as long as there is a factotum running. Please see https://godoc.org/github.com/knusbaum/go9p/fs#WithAuth for more info about the `WithAuth` `Option`, and see the ramfs example to see an example of the use of `Option`s with `NewFS`:
https://github.com/knusbaum/go9p/blob/a017ccff31434a40ff243102ee12fa13751ad8b3/examples/ramfs/main.go#L10-L12
